"""Target-model traces: the training data every learned drafter is fitted on.

In production this is what ``speculators`` extracts from vLLM: token ids
plus the verifier's hidden states (and, for distillation, its logits) on
*responses generated by the target itself* (on-policy data).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from specdec.models import ToyLM
from specdec.ngram import find_suffix_match
from specdec.sampling import softmax


@dataclass
class Trace:
    tokens: np.ndarray  # (T,)
    feats: np.ndarray  # (T, 2H) hidden states [h1; h2] after each token
    probs: np.ndarray  # (T, V) target p(x_{t+1} | x_{<=t})
    copy_lam: np.ndarray  # (T,) copy weight at each position
    copy_end: np.ndarray  # (T,) index of copy source token, -1 if none


def collect_traces(target: ToyLM, corpus: list[list[int]]) -> list[Trace]:
    traces = []
    max_n = target.config.copy_max_n
    for seq in corpus:
        sess = target.session(seq)
        feats = np.array([np.concatenate(s) for s in sess.states])
        lams, ends, probs = [], [], []
        for t in range(len(seq)):
            n, end = find_suffix_match(seq[: t + 1], 1, max_n)
            lam = target.config.copy_strength * n / max_n if n else 0.0
            base = softmax(target.lm_head(sess.states[t][1]))
            if lam:
                base = (1 - lam) * base
                base[seq[end]] += lam
            lams.append(lam)
            ends.append(end)
            probs.append(base)
        traces.append(Trace(np.array(seq), feats, np.array(probs), np.array(lams), np.array(ends)))
    return traces
