#!/usr/bin/env bash
# Resource #4: train your own drafter with vllm-project/speculators, then serve it
# with a plain `vllm serve`. Needs GPUs. Commands follow the speculators
# "Train a Speculator" tutorial; check it for the current flags of your version:
# https://docs.vllm.ai/projects/speculators/en/latest/
#
# Algorithms: eagle3 (default, most mature), peagle, dflash, dspark, mtp.
#
#   ALGO=dspark TARGET=Qwen/Qwen3-8B DATA=./target_responses.jsonl \
#     examples/04_train_drafter_speculators.sh
#
# Training data MUST be responses generated by the target model itself (on-policy),
# ideally sampled from your own production prompts.
set -euo pipefail
ALGO=${ALGO:-eagle3}
TARGET=${TARGET:-Qwen/Qwen3-8B}
DATA=${DATA:-./target_responses.jsonl}
WORK=${WORK:-./output}
VLLM_GPUS=${VLLM_GPUS:-0,1}
TRAIN_GPUS=${TRAIN_GPUS:-2,3}
NPROC=$(awk -F, '{print NF}' <<< "$TRAIN_GPUS")

# 0) Two environments (dependencies conflict otherwise):
#    uv venv speculators_venv && . speculators_venv/bin/activate && uv pip install speculators
#    uv venv vllm_venv        && . vllm_venv/bin/activate        && uv pip install vllm
# Run from a clone of https://github.com/vllm-project/speculators (for scripts/launch_vllm.py).

echo "== 1) prepare data (speculators venv)"
speculators prepare-data --model "$TARGET" --data "$DATA" --output "$WORK" \
  --max-samples "${MAX_SAMPLES:-5000}" --seq-length "${SEQ_LEN:-8192}"

echo "== 2) launch the verifier in vLLM for hidden-state extraction (vllm venv, separate terminal)"
echo "   CUDA_VISIBLE_DEVICES=$VLLM_GPUS python scripts/launch_vllm.py $TARGET -- --data-parallel-size 2 --port 8000"
read -r -p "   press enter once vLLM is up ... " _

echo "== 3) train ($ALGO, online mode: hidden states streamed from vLLM)"
ALGO_ARGS=()
case "$ALGO" in
  eagle3) ;;
  peagle) ALGO_ARGS=(--speculator-type peagle --num-layers 4 --num-depths 4 --no-norm-before-residual
                     --scheduler-type cosine --lr 6e-4) ;;
  dflash) ALGO_ARGS=(--speculator-type dflash --num-layers 5 --lr 3e-4) ;;
  dspark) ALGO_ARGS=(--speculator-type dspark --num-layers 5 --lr 3e-4 --loss-fn '{"ce": 0.1, "tv": 0.9}') ;;
  *) echo "unsupported ALGO=$ALGO (mtp needs a verifier with native MTP layers; see the tutorial)" >&2; exit 2 ;;
esac
CUDA_VISIBLE_DEVICES=$TRAIN_GPUS torchrun --standalone --nproc_per_node "$NPROC" \
  -m speculators.train \
  --verifier-name-or-path "$TARGET" \
  --data-path "$WORK" \
  --save-path "$WORK/checkpoints" \
  --draft-vocab-size 32000 \
  --epochs "${EPOCHS:-5}" \
  --total-seq-len "${SEQ_LEN:-8192}" \
  --vllm-endpoint http://localhost:8000/v1 \
  --on-missing generate \
  --on-generate delete \
  "${ALGO_ARGS[@]}"

echo "== 4) stop the extraction server, then serve the drafter: the checkpoint is self-describing"
echo "   vllm serve $WORK/checkpoints/checkpoint_best --port 8001"
echo "== 5) measure on your own traffic"
echo "   scripts/compare_on_traffic.sh my_traffic.jsonl baseline=http://localhost:8000/v1 $ALGO=http://localhost:8001/v1"
